ELATUS_ROOT_PATH = 	$(ELATUS_PATH)/ELATUS

ELATUS_LCD = $(ELATUS_ROOT_PATH)/Treiber/Peripherie/lcd.c

ELATUS_UART = $(ELATUS_ROOT_PATH)/Treiber/Schnittstellen/uart.c

ELATUS_I2C_SL =$(ELATUS_ROOT_PATH)/Treiber/Schnittstellen/i2c_slave.c

ELATUS_ADW = $(ELATUS_ROOT_PATH)/Treiber/Schnittstellen/adw.c
